id: 061737dcff2a47379e6b96f801417894
initial_creation_type: ocr
source_metadata:
  volumes:
    87a4fa973b07446ebd1df0ce1f3f1288:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ''
      total_pages: 1539
      volume_number: 1
